### ISSUE TITLE
Add feature to control the vanillia game time speed

### ISSUE THREAD

**Issue by YKDZ** [M0diis/VenturaCalendar#1]
At present, the plug-in can not specify the passing speed of time. I propose to add a system to control time:
TimeConfig.yml:
time-systems:
  default:
    world-name: world
    world-time:
        sunrise: 6:00
        noon: 12:00
        sunset: 18:00
        midnight: 0:00
In this way, players will not see the sun set at 12 o'clock.

**Comment by M0diis** [comment]
This is a quite hard thing to do.
The time in sun/moon position depends on the time ticks, which go from 0 to 23999.
The date is calculated using world ticks, so if it's manipulated somehow - then the timing would be off.

**Comment by YKDZ** [comment]
Yes, maybe you can control the position of the sun by disabling the passage of time...
Sorry, I'm not able to provide more opinions and suggestions)

**Comment by M0diis** [comment]
There is no real way to modify the speed of the world time except adding a timer which would add or subtract several ticks to or from the world time.

This would cause the time to faster on it's own.
I will not be working on this, unfortunately.

I appreciate the suggestion regardless.

**Comment by M0diis** [comment]
@YKDZ 

I've added an option to sync game-time with real-time, if it's enabled.
That means if it's noon in real life, it's noon in-game.
